Repository supermetrics-public/pecl-jsonpath, pull requests merged in 2021-07, with the labels that each got.

#126 Replace strdup->estrdup
  jsonpath.c
Labels: chore

#127 Add scripts and docs for code quality tooling
  Makefile.frag
  README.md
  pre-commit
Labels: chore, feature

#128 Change license from MIT to PHP to conform to PECL guidelines for PHP extensions
  LICENSE
Labels: chore

#130 Perform clang-format check automatically on pushes to the repository
  .github/workflows/clang_format_lint.yml
Labels: feature

#129 Update links following repository name change
  .github/workflows/code_coverage.yml
  README.md
Labels: chore

#132 Update benchmark chart with latest software versions, new benchmarks, and OPCache + JIT enabled
  benchmark.png
Labels: chore

#133 Update license information in README to reflect license change from MIT to PHP
  README.md
Labels: chore, documentation
