Repository supermetrics-public/pecl-jsonpath, pull requests merged in 2021-06, with the labels that each got.

#108 Fix double-free detected by valgrind
  src/jsonpath/interpreter.c
Labels: bugfix

#109 Fix remaining unit tests
  tests/comparison_filter/029.phpt
  tests/comparison_filter/030.phpt
  tests/comparison_filter/036.phpt
  tests/comparison_filter/037.phpt
  tests/comparison_filter/040.phpt
  tests/comparison_filter/059.phpt
  tests/comparison_filter/060.phpt
  tests/comparison_filter/071.phpt
Labels: bugfix, chore

#110 Bump version number to 0.9.0
  php_jsonpath.h
Labels: chore

#111 Add performance benchmark chart to README
  README.md
  benchmark.png
Labels: chore

#117 Fix IDE warnings, cleanup
  .clang-format
  jsonpath.c
  src/jsonpath/interpreter.c
  src/jsonpath/lexer.c
  src/jsonpath/lexer.h
  src/jsonpath/parser.c
  src/jsonpath/parser.h
Labels: bugfix, chore

#118 Bump version number to 0.9.1
  php_jsonpath.h
Labels: chore
